version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      dockerfile: Dockerfile
      context: ./
      target: development
    container_name: backendsever
    command: sh -c ' && npx prisma migrate dev && yarn dev'
    restart: always
    ports:
      - '5000:5000'
    env_file:
      - .env.development
    depends_on:
      - postgres
    networks:
      - backend-network
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
networks:
  backend-network:
    name: express-template

volumes:
  pgdata:
